export const PROJECTS =
    [
        {
        id: 0,
        name:'Sitio Web del Club',
        image: '/assets/images/club3.png',
        category: 'mains',
        label:'Hot',
        price:'4.99',
        featured: true,
        description:'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
        },
        {
        id: 1,
        name:'PlanTV',
        image: '/assets/images/directiva.png',
        category: 'appetizer',
        label:'',
        price:'4.99',
        featured: true,
        description:'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
        }, 
        {
        id: 2,
        name:'PlanTV',
        image: '/assets/images/directiva.png',
        category: 'appetizer',
        label:'',
        price:'4.99',
        featured: true,
        description:'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
        },
        {
        id: 3,
        name:'PlanTV',
        image: '/assets/images/club3.png',
        category: 'appetizer',
        label:'',
        price:'4.99',
        featured: true,
        description:'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
        },   
    ];